### ISSUE TITLE
add new value feature -- pull request?

### ISSUE THREAD

**Issue by andytwoods** [karantanwar/flutter_search_panel#5]
Hi, 
do you want this feature? Happy to make a pull request. Afraid I'm rather a Flutter newbie though, but I think my mods are ok.

![image](https://user-images.githubusercontent.com/595166/46945889-fe399780-d06d-11e8-8b59-ebc63eed23f5.png)

**Comment by karantanwar** [comment]
please do.... I was thinking about add this feature but i couldn't get the time to do that...
